# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastai_course',
                'doc_host': 'https://daniilgaltsev.github.io',
                'git_url': 'https://github.com/daniilgaltsev/fastai_course',
                'lib_path': 'miniai'},
  'syms': {'miniai.core': {'miniai.core.foo': ('core.html#foo', 'miniai/core.py')}}}
