# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastai_course',
                'doc_host': 'https://daniilgaltsev.github.io',
                'git_url': 'https://github.com/daniilgaltsev/fastai_course',
                'lib_path': 'miniai'},
  'syms': { 'miniai.core': {'miniai.core.foo': ('core.html#foo', 'miniai/core.py')},
            'miniai.datasets': { 'miniai.datasets.collate_dict': ('datasets.html#collate_dict', 'miniai/datasets.py'),
                                 'miniai.datasets.get_grid': ('datasets.html#get_grid', 'miniai/datasets.py'),
                                 'miniai.datasets.inplace': ('datasets.html#inplace', 'miniai/datasets.py'),
                                 'miniai.datasets.show_image': ('datasets.html#show_image', 'miniai/datasets.py'),
                                 'miniai.datasets.show_images': ('datasets.html#show_images', 'miniai/datasets.py'),
                                 'miniai.datasets.subplots': ('datasets.html#subplots', 'miniai/datasets.py')}}}
